import binascii

# default seed: 0000000000000000
tpl = '''
{
  "notes":"generated by generator.py",
  "seed":"%s",
  "tv_size":16,
  "tv_count":67108864,
  "file_name":"AES_r10_b16.bin",
  "stdout": true,
  "stream":{
    "type": "block",
    "init_frequency": "only_once",
    "algorithm": "AES",
    "round": 10,
    "block_size": 16,
    "plaintext": {
      "type": "xor_stream",
      "source": {
        "type": "tuple_stream",
        "sources": [
          {
            "type": "counter",
            "output_size": 16
          },
          {
            "type": "single_value_stream",
            "output_size": 16,
            "source": {
                "type": "pcg32_stream",
                "output_size": 16
            }
          }
        ]
      }
    },
    "key_size": 16,
    "key": {
      "type": "pcg32_stream"
    },
    "iv_size": 16,
    "iv":{
      "type": "false_stream"
    }
  }
}
'''

num_experiments = 1000  # 10_000
seed_offset = 1
name_list = []

for coff in range(seed_offset, seed_offset + num_experiments):
    seedb = binascii.hexlify(coff.to_bytes(8, byteorder='big')).decode('utf8')
    ctpl = tpl % (seedb,)
    name_tpl = 'aes10-randctr-seed-%s.json' % (seedb,)
    name_list.append(name_tpl)
    with open(name_tpl, 'w+') as fh:
        fh.write(ctpl)

with open('__enqueue.sh', 'w+') as fh:
    fh.write("#!/bin/bash\n")
    for name in name_list:
        fh.write("submit_experiment --dieharder --email ph4r05@gmail.com  --name 't04-dieharder-%s' --cfg 'dieharder-paper-1GB.json' --cryptostreams-config '%s'\n" % (name, name))
